// White-label settings. Copy this file per deployment and change only these values.
window.WSP_CLIENT_CONFIG = {
  clientName: "SkillSet SA",
  appName: "Training Reporting Hub",
  preparedFor: "SkillSet SA",
  tagline: "Reporting · Analytics · Insight",
  logo: "",
  logoAlt: "SkillSet SA",
  logoInitials: "SkillSet SA",
  primaryColor: "#063c25",
  secondaryColor: "#0e7a45",
  accentColor: "#ffcc00",
  financialYear: "2026/27",
  environmentLabel: "Demo data only",
  privacyNotice: "Synthetic records only. A production client version should run inside the client's Microsoft 365 environment.",
  subtitle: "Workbook import · controlled WSP / ATR workflow · Microsoft 365 pilot pattern.",
  heroEyebrow: "SkillSet SA · Training reporting diagnostic",
  heroTitle: "Find WSP / ATR risk before submission pressure starts.",
  heroIntro: "Load a workbook, expose planning gaps, evidence weaknesses and reporting actions, then turn the result into a controlled Microsoft 365 pilot.",
  heroFootnote: "Public demo: workbook inspection runs locally in this browser. Production data belongs in SharePoint, Dataverse or the client's approved Microsoft 365 environment.",
  sidebarFooterTitle: "Microsoft 365 pilot path",
  sidebarFooterText: "Workbook scan · workflow · reporting",
  budgetEstimateNote: "Demo planning estimate only. Final financial, SETA or compliance values must be confirmed through the client's approved process.",
  workbookIntro: "Stage the sample workbook or inspect a safe Excel / CSV file in this browser. The demo does not upload workbook data to a server.",
  storageKey: "skillset-wsp-training-hub-v1"
};
