// White-label settings. Copy this file per deployment and change only these values.
window.WSP_CLIENT_CONFIG = {
  clientName: "SkillSet SA",
  appName: "Training Reporting Hub",
  preparedFor: "SkillSet SA",
  tagline: "Reporting · Analytics · Insight",
  logo: "",
  logoAlt: "SkillSet SA",
  logoInitials: "SkillSet SA",
  primaryColor: "#063c25",
  secondaryColor: "#0e7a45",
  accentColor: "#ffcc00",
  financialYear: "2026/27",
  environmentLabel: "Demo data only",
  privacyNotice: "Synthetic records only. A production client version should run inside the client's Microsoft 365 environment.",
  subtitle: "Workbook import · controlled WSP / ATR workflow · Microsoft 365 pilot pattern.",
  heroEyebrow: "SkillSet SA · WSP / ATR reporting system",
  heroTitle: "Turn training records into a controlled reporting workflow.",
  heroIntro: "A practical training reporting hub for teams that still depend on spreadsheets, manual bookings and scattered evidence.",
  heroFootnote: "Use this public demo for walkthroughs only. Production data belongs in a client-controlled Microsoft 365 environment.",
  sidebarFooterTitle: "Pilot workspace",
  sidebarFooterText: "Excel import · workflow · reporting",
  budgetEstimateNote: "Demo planning estimate only. Final financial, SETA or compliance values must be confirmed through the client's approved process.",
  workbookIntro: "Stage the sample workbook, upload a CSV export, or load a safe Excel workbook. The public demo reads the file locally in your browser; do not use private client data here.",
  storageKey: "skillset-wsp-training-hub-v1"
};
